export const moviesGenres = [
  { id: 28, name: "Action" },
  { id: 12, name: "Adventure" },
  { id: 16, name: "Animation" },
  { id: 35, name: "Comedy" },
  { id: 80, name: "Crime" },
  { id: 99, name: "Documentary" },
  { id: 18, name: "Drama" },
  { id: 10751, name: "Family" },
  { id: 14, name: "Fantasy" },
  { id: 36, name: "History" },
  { id: 27, name: "Horror" },
  { id: 10402, name: "Music" },
  { id: 9648, name: "Mystery" },
  { id: 10749, name: "Romance" },
  { id: 878, name: "Science Fiction" },
  { id: 10770, name: "TV Movie" },
  { id: 53, name: "Thriller" },
  { id: 10752, name: "War" },
  { id: 37, name: "Western" },
];

export const TVGenres = [
  { id: 10759, name: "Action & Adventure" },
  { id: 16, name: "Animation" },
  { id: 35, name: "Comedy" },
  { id: 80, name: "Crime" },
  { id: 99, name: "Documentary" },
  { id: 18, name: "Drama" },
  { id: 10751, name: "Family" },
  { id: 10762, name: "Kids" },
  { id: 9648, name: "Mystery" },
  { id: 10763, name: "News" },
  { id: 10764, name: "Reality" },
  { id: 10765, name: "Sci-Fi & Fantasy" },
  { id: 10766, name: "Soap" },
  { id: 10767, name: "Talk" },
  { id: 10768, name: "War & Politics" },
  { id: 37, name: "Western" },
];

const tvdetils = {
  adult: false,
  backdrop_path: "/m0bV3qBiJBBlpFaaKjwHo13MVjm.jpg",
  created_by: [],
  episode_run_time: [60],
  first_air_date: "2005-01-03",
  genres: [
    { id: 35, name: "Comedy" },
    { id: 10767, name: "Talk" },
  ],
  homepage: "",
  id: 14981,
  in_production: false,
  languages: ["en"],
  last_air_date: "2014-12-19",
  last_episode_to_air: {
    id: 2763686,
    overview: "In this final episode Craig welcomes comedian Jay Leno.",
    name: "Jay Leno",
    vote_average: 9,
    vote_count: 1,
    air_date: "2014-12-19",
    episode_number: 73,
    episode_type: "finale",
    production_code: "",
    runtime: 60,
    season_number: 11,
    show_id: 14981,
    still_path: null,
  },
  name: "The Late Late Show with Craig Ferguson",
  next_episode_to_air: null,
  networks: [
    {
      id: 16,
      logo_path: "/wju8KhOUsR5y4bH9p3Jc50hhaLO.png",
      name: "CBS",
      origin_country: "US",
    },
  ],
  number_of_episodes: 2057,
  number_of_seasons: 11,
  origin_country: ["US"],
  original_language: "en",
  original_name: "The Late Late Show with Craig Ferguson",
  overview:
    "The Late Late Show with Craig Ferguson is an American late-night talk show hosted by Scottish American comedian Craig Ferguson, who is the third regular host of the Late Late Show franchise. It follows Late Show with David Letterman in the CBS late-night lineup, airing weekdays in the US at 12:37 a.m. It is taped in front of a live studio audience from Monday to Friday at CBS Television City in Los Angeles, California, directly above the Bob Barker Studio. It is produced by David Letterman's production company Worldwide Pants Incorporated and CBS Television Studios.\n" +
    "\n" +
    "Since becoming host on January 3, 2005, after Craig Kilborn and Tom Snyder, Ferguson has achieved the highest ratings since the show's inception in 1995. While the majority of the episodes focus on comedy, Ferguson has also addressed difficult subject matter, such as the deaths of his parents, and undertaken serious interviews, such as one with Desmond Tutu, which earned the show a 2009 Peabody Award.",
  popularity: 2906.336,
  poster_path: "/gGC7zSDgG0FY0MbM1pjfhTCWQBI.jpg",
  production_companies: [],
  production_countries: [
    { iso_3166_1: "US", name: "United States of America" },
  ],
  seasons: [
    {
      air_date: "2005-01-03",
      episode_count: 141,
      id: 61527,
      name: "Season 1",
      overview: "",
      poster_path: null,
      season_number: 1,
      vote_average: 8,
    },
    {
      air_date: "2005-09-12",
      episode_count: 205,
      id: 61526,
      name: "Season 2",
      overview: "",
      poster_path: null,
      season_number: 2,
      vote_average: 0,
    },
    {
      air_date: "2006-09-11",
      episode_count: 207,
      id: 61525,
      name: "Season 3",
      overview: "",
      poster_path: null,
      season_number: 3,
      vote_average: 9,
    },
    {
      air_date: "2007-09-10",
      episode_count: 171,
      id: 183638,
      name: "Season 4",
      overview: "",
      poster_path: null,
      season_number: 4,
      vote_average: 7.5,
    },
    {
      air_date: "2008-09-01",
      episode_count: 210,
      id: 183639,
      name: "Season 5",
      overview: "",
      poster_path: null,
      season_number: 5,
      vote_average: 7.5,
    },
    {
      air_date: "2009-08-31",
      episode_count: 210,
      id: 61524,
      name: "Season 6",
      overview: "",
      poster_path: null,
      season_number: 6,
      vote_average: 7.5,
    },
    {
      air_date: "2010-08-30",
      episode_count: 210,
      id: 61523,
      name: "Season 7",
      overview: "",
      poster_path: null,
      season_number: 7,
      vote_average: 7.9,
    },
    {
      air_date: "2011-08-22",
      episode_count: 210,
      id: 183640,
      name: "Season 8",
      overview: "",
      poster_path: null,
      season_number: 8,
      vote_average: 7.4,
    },
    {
      air_date: "2012-08-27",
      episode_count: 210,
      id: 183641,
      name: "Season 9",
      overview: "",
      poster_path: null,
      season_number: 9,
      vote_average: 7.8,
    },
    {
      air_date: "2013-09-02",
      episode_count: 210,
      id: 61595,
      name: "Season 10",
      overview: "",
      poster_path: null,
      season_number: 10,
      vote_average: 7.6,
    },
    {
      air_date: "2014-09-01",
      episode_count: 73,
      id: 183642,
      name: "Season 11",
      overview: "",
      poster_path: null,
      season_number: 11,
      vote_average: 7.8,
    },
  ],
  spoken_languages: [
    { english_name: "English", iso_639_1: "en", name: "English" },
  ],
  status: "Ended",
  tagline: "",
  type: "Talk Show",
  vote_average: 6.831,
  vote_count: 89,
};
const moviedetils = {
  adult: false,
  backdrop_path: "/qjoX7hl721FOiyeHsDkeQ6rFVLl.jpg",
  belongs_to_collection: {
    id: 1022790,
    name: "Inside Out Collection",
    poster_path: "/Apr19lGxP7gm6y2HQX0kqOXTtqC.jpg",
    backdrop_path: "/bR8H6S3Jc2vhPvz2VWX0dQ3XTFV.jpg",
  },
  budget: 200000000,
  genres: [
    { id: 16, name: "Animation" },
    { id: 10751, name: "Family" },
    { id: 18, name: "Drama" },
    { id: 12, name: "Adventure" },
    { id: 35, name: "Comedy" },
  ],
  homepage: "https://movies.disney.com/inside-out-2",
  id: 1022789,
  imdb_id: "tt22022452",
  origin_country: ["US"],
  original_language: "en",
  original_title: "Inside Out 2",
  overview:
    "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
  popularity: 2538.214,
  poster_path: "/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
  production_companies: [
    {
      id: 3,
      logo_path: "/1TjvGVDMYsj6JBxOAkUHpPEwLf7.png",
      name: "Pixar",
      origin_country: "US",
    },
    {
      id: 2,
      logo_path: "/wdrCwmRnLFJhEoH8GSfymY85KHT.png",
      name: "Walt Disney Pictures",
      origin_country: "US",
    },
  ],
  production_countries: [
    { iso_3166_1: "US", name: "United States of America" },
  ],
  release_date: "2024-06-11",
  revenue: 0,
  runtime: 97,
  spoken_languages: [
    { english_name: "English", iso_639_1: "en", name: "English" },
  ],
  status: "Released",
  tagline: "Make room for new emotions.",
  title: "Inside Out 2",
  video: false,
  vote_average: 7.181,
};

export const filtertagsTv = ["popularity", "vote_average"];
export const filtertagsMovie = [
  "popularity",
  "vote_average",
  "now_playing",
  "upcoming",
];
